# Generated by Django 5.2.7 on 2025-10-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseresult',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseresult',
            name='student',
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='exercise_title',
            field=models.CharField(default='Prueba', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='student_name',
            field=models.CharField(default='Estudiante', max_length=100),
            preserve_default=False,
        ),
    ]
