# Generated by Django 5.2.7 on 2025-10-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_exerciseresult_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
